name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          build-tools-version: 31.0.0

      - name: Get Buildozer Action
        uses: digreatbrian/buildozer-action@v2
        with:
          buildozer-cmd: buildozer -v android debug
