name: Build APK
on: [push, workflow_dispatch] # Сборка запускается при каждом сохранении кода или вручную

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Get Buildozer Action
        uses: digreatbrian/buildozer-action@v2
        with:
          buildozer_version: stable
          buildozer-cmd: buildozer -v android debug
